DECLARE @ExportSQL nvarchar(max);

SET @ExportSQL = 'EXEC ..xp_cmdshell ''bcp "SELECT        
P1.PJ,
P1.FICHA,
--T1.ID_TRAMITACAO IDTRAMITACAO,
--    T1.arquivo ARQUIVO_TRAMITAÇAO,
P1.arquivo ARQUIVO_PROCESSO,
V1.descricao NM_OJ,
--LTRIM(RTRIM(P1.NUMERO_INTEGRACAO)) NRINTEGRACAO,
--    LTRIM(RTRIM(T1.EVENTO)) SGEVENTO,
--        LTRIM(RTRIM(E1.DESCRICAO)) NMEVENTO,
--    P1.entrada DATA_REGISTRO_PROCESSO,
P1.juizo JUIZO_PROCESSO,
P1.oj_numero ORGAO_JULGADOR_NUM,
P1.oj_sigla ORGAO_JULGADOR_SIGLA,
--    R1.DATA_REGISTRO DATA_REGISTRO,
--DATEPART(HOUR,R1.DATA_REGISTRO) HRLANCAMENTO,
--    T1.DATA_HORA_LAN DTEVENTO,
--    T1.AG_DATA_HORA DTAGENDA,
--    T1.UPDATE_DATA_HORA DTULTIMOUPDATE,
--    T1.PRAZO_DATA_FINAL DTPRAZOFATAL,
--    UPPER(LTRIM(RTRIM(A1.DESCRICAO))) TPAGENDAMENTO,
--    UPPER(LTRIM(RTRIM(S1.DESCRICAO))) STATUSEVENTO,
--    U1.NOME ATUALIZADOPOR,
--    UPPER(LTRIM(RTRIM(T1.cumprido_por))) REALIZADO_POR,
--    U6.nome REALIZADO_POR_DESC,
--   T1.cumprido_em REALIZADO_EM,
--    Y1.descricao RESULTADO,
--CASE
--    WHEN T1.EVENTO IN (''''BOGSL'''',''''BOGSA'''',''''BOGAD'''',''''BODPR'''',''''BOGSZ'''',''''BOGST'''',''''BOSBI'''') THEN ''''SOLICITACAO''''
--    WHEN T1.EVENTO IN (''BOGAC'',''BOGAA'',''BODAA'',''BOGAZ'',''BOGAT'',''BOGAX'') THEN ''ACOMPANHAMENTO''
--    WHEN T1.EVENTO IN (''BOGCP'') THEN ''COMPLIANCE''
--    WHEN T1.EVENTO IN (''BOGRV'',''BOGRT'') THEN ''AG. TERCEIRO''
--    WHEN T1.EVENTO IN (''BOMPS'') THEN ''MOVIMENTACAO SIGA''
--END TPEVENTO,

---        CASE
--        WHEN U2.NOME IS NULL THEN P2.NOME
--        ELSE P2.NOME
--    END AGENDADOPARA,
--CASE
--WHEN E1.ID_CELULA IS NULL THEN ''AGENDA DIRETA''
--WHEN E1.ID_CELULA IS NOT NULL AND T1.AG_PESSOA_ATRIBUIDO IS NULL THEN ''NAO ATRIBUIDO''
--ELSE LTRIM(RTRIM(U3.NOME))
--END ATRIBUIDOPARA_CATEG,
--U3.NOME ATRIBUIDOPARA,
--        R1.DATA_AGENDA DTAGENDAORIGINAL,
--DATEDIFF(DAY,R1.DATA_AGENDA,T1.AG_DATA_HORA) QTDIASREAGENDAMENTO,
--LTRIM(RTRIM(G3.DESCRICAO)) GRUPOUSUARIOAGENDADOPARA,
--LTRIM(RTRIM(G1.DESCRICAO)) GRUPOUSUARIOSOLICITANTE,
LTRIM(RTRIM(P1.NUMERO_PROCESSO)) NRPROCESSO,
--LTRIM(RTRIM(P1.LOC_SIGLA)) LOCALIZADOR,
LTRIM(RTRIM(P3.NOME)) AUTOR,
LTRIM(RTRIM(P4.NOME)) REU,
--LTRIM(RTRIM(G2.DESCRICAO)) GRUPOPROCESSO,
LTRIM(RTRIM(P5.NOME)) UNIDADE,
--        LTRIM(RTRIM(P6.NOME)) NMADVRESPONSAVEL,
--        p1.acao ACAO,
--        Z1.descricao DESC_ACAO,
--        p1.valor_causa VALOR_CAUSA,
--CASE
--    WHEN P1.ELETRONICO = 0 THEN ''FISICO''
--    ELSE ''ELETRONICO''
--END FLAGELETRONICOFISICO,
CASE
WHEN UPPER(LTRIM(RTRIM(J1.DESCRICAO))) IS NULL THEN ''SEM COMARCA'' 
ELSE UPPER(LTRIM(RTRIM(J1.DESCRICAO)))
END COMARCA,
CASE
WHEN LTRIM(RTRIM(J1.ESTADO)) IS NULL THEN ''SEM COMARCA''
ELSE LTRIM(RTRIM(J1.ESTADO))
END UFCOMARCA,
--    CASE 
--        WHEN LEN(RTRIM(LTRIM(REPLACE(SUBSTRING(T1.TEXTO,1,500),CHAR(13) + CHAR(10),'' '')))) > 300 THEN RTRIM(LTRIM(REPLACE(SUBSTRING(T1.TEXTO,1,300),CHAR(13) + CHAR(10),'' ''))) + ''*-* LEIA O RESTANTE NO CPJ *-*''
--        ELSE RTRIM(LTRIM(REPLACE(SUBSTRING(T1.TEXTO,1,300),CHAR(13) + CHAR(10),'' '')))
--    END COMPLEMENTO,
--P1.PESSOA_RESPONSAVEL,
--T1.AG_PESSOA,
--T1.AG_PESSOA_ATRIBUIDO,
--T1.AG_PESSOA_SOLICITANTE,
--LTRIM(RTRIM(C1.DESCRICAO)) LOCALTRABALHO,
--LTRIM(RTRIM(A1.DESCRICAO)) DESCRICAO_ANDAMENTO,
LTRIM(RTRIM(G2.DESCRICAO)) DESCRICAO_GRUPO_TRABALHO
--,    GETDATE() DTHRCENARIO 

--INTO TBL_BRC_SOPIII_PBI

FROM 
cpjwcs.DBO.CAD_PROCESSO P1 WITH (NOLOCK)
--    LEFT JOIN cpjwcs.DBO.CAD_TRAMITACAO T1 WITH (NOLOCK) ON /* DADOS DO PROCESSO */
--        P1.FICHA = T1.FICHA AND
--        P1.INCIDENTE = T1.INCIDENTE AND
--        P1.ARQUIVO = T1.ARQUIVO

--    LEFT JOIN cpjwcs.DBO.TBL_BRC_REGISTRO_TRAMITACAO R1 WITH (NOLOCK) ON /* DATA REAL DE LANCAMENTO DO EVENTO + DATA ORIGINAL AGENDA */
--        T1.ID_TRAMITACAO = R1.ID_TRAMITACAO

--    LEFT JOIN cpjwcs.DBO.TAB_EVENTO E1 WITH (NOLOCK) ON /* DADOS DO EVENTO */
--        T1.EVENTO = E1.SIGLA

--            LEFT JOIN cpjwcs.DBO.TAB_ANDAMENTO A1 WITH (NOLOCK) ON /* TIPO DO EVENTO */
--                E1.TIPO = A1.CODIGO

--        LEFT JOIN cpjwcs.[dbo].[tab_acao] Z1 WITH (NOLOCK) ON /* DESCRIÇÃO DA AÇÃO */
--            P1.acao = Z1.sigla

--        LEFT JOIN cpjwcs.[dbo].[tab_resultado] Y1 WITH (NOLOCK) ON /* SENTENÇA */
--            P1.resultado_situacao = Y1.codigo

--            LEFT JOIN cpjwcs.DBO.TRAMITACAO_STATUS S1 WITH (NOLOCK) ON /* STATUS TRAMITACAO */
--                T1.AG_CUMPRIDO = S1.CODIGO

--        LEFT JOIN cpjwcs.DBO.USUARIO U1 WITH (NOLOCK) ON /* ATUALIZADO POR */
--        T1.UPDATE_USUARIO = U1.ID_USUARIO

--        LEFT JOIN cpjwcs.DBO.CAD_PESSOA P2 WITH (NOLOCK) ON /* AGENDADO PARA PESSOA */
--            T1.AG_PESSOA = P2.CODIGO

--        LEFT JOIN cpjwcs.DBO.USUARIO U2 WITH (NOLOCK) ON    /* AGENDADO PARA USUARIO */
--            P2.CODIGO = U2.PESSOA_AGENDA

--        LEFT JOIN cpjwcs.DBO.TAB_GRUPO_TRABALHO G3 WITH (NOLOCK) ON /* GRUPO TRABALHO AGENDADO PARA */
--            U2.GRUPO_USU = G3.CODIGO

--    LEFT JOIN cpjwcs.DBO.USUARIO U3 WITH (NOLOCK) ON    /* ATRIBUIDO PARA USUARIO */
--        T1.AG_PESSOA_ATRIBUIDO = U3.PESSOA_AGENDA

--        LEFT JOIN cpjwcs.DBO.USUARIO U4 WITH (NOLOCK) ON /* SOLICITANTE USUARIO */
--            T1.AG_PESSOA_SOLICITANTE = U4.PESSOA_AGENDA

--        LEFT JOIN cpjwcs.DBO.USUARIO U6 WITH (NOLOCK) ON /* CUMPRIDO POR */
--        T1.cumprido_por = U6.ID_USUARIO

--    LEFT JOIN cpjwcs.DBO.TAB_GRUPO_TRABALHO G1 WITH (NOLOCK) ON /* GRUPO TRABALHO SOLICITANTE */
--        U4.GRUPO_USU = G1.CODIGO

--LEFT JOIN VW_BRC_REAGENDAMENTO_01 R2 ON    /* REAGENDAMENTOS */
--    T1.ID_TRAMITACAO = R2.IDTRAMITACAO

LEFT JOIN cpjwcs.DBO.CAD_PESSOA P3 WITH (NOLOCK) ON /* AUTOR */
P1.PRIMEIRO_AUTOR = P3.CODIGO 

LEFT JOIN cpjwcs.DBO.CAD_PESSOA P4 WITH (NOLOCK) ON /* REU */
P1.PRIMEIRO_REU = P4.CODIGO

LEFT JOIN cpjwcs.DBO.TAB_GRUPO_TRABALHO G2 WITH (NOLOCK) ON /* GRUPO TRABALHO PROCESSO */
P1.GRUPO_TRABALHO = G2.CODIGO 

LEFT JOIN cpjwcs.DBO.UNIDADE U5 WITH (NOLOCK) ON /* UNIDADE PROCESSO */
P1.ID_UNIDADE = U5.ID_UNIDADE 

LEFT JOIN cpjwcs.DBO.CAD_PESSOA P5 WITH (NOLOCK) ON /* UNIDADE PROCESSO PESSOA */
U5.ID_PESSOA = P5.CODIGO

LEFT JOIN cpjwcs.DBO.TAB_JUIZO J1 WITH (NOLOCK) ON /* JUIZO */
P1.JUIZO = J1.SIGLA

--        LEFT JOIN cpjwcs.DBO.CAD_PESSOA P6 WITH (NOLOCK) ON /* ADVOGADO RESPONSAVEL */
--            P1.PESSOA_RESPONSAVEL = P6.CODIGO

--    LEFT JOIN cpjwcs.DBO.TAB_CENTRO_CUSTO C1 WITH (NOLOCK) ON /* LOCAL DE TRABALHO */
--        U3.USR_CENTRO_CUSTO = C1.CODIGO

LEFT JOIN cpjwcs.dbo.tab_orgao_julgador V1 WITH (NOLOCK) ON /* órgão julgador */
p1.oj_sigla= V1.sigla

--LEFT JOIN TBL_BRC_BACKOFFICE_EVENTO_CPJ T2 ON /* CLASSIFICACAO DO EVENTO */
--    T1.EVENTO = T2.SIGLA


--        AND             T1.EVENTO IN (SELECT SIGLA FROM TBL_BRC_BACKOFFICE_EVENTO_CPJ) /* CONSIDERA EVENTOS DO BACK OFFICE */

WHERE
-- ((E1.TIPO NOT IN (1)) or (E1.TIPO IN (1) and T1.EVENTO IN (''CMAPF'',''CMSDF'',''CMADF'',''S3ADE'',''CMSFV'',''CMSPF'',''S3APF'',''CMAFV'',''S3ACF''))) AND 
--    T1.AG_CUMPRIDO NOT IN (1,2) 
-- P1.GRUPO_TRABALHO IN (284,287,288,289,290,297,298,299,303,309,313,316,319,322,19759,19758, 19762, 19763, 19764)  
P1.GRUPO_TRABALHO IN (322, 19759,284,287,288,309,313,316,319,298,299,303,290,297, 19758, 19762, 19763, 19764)  

--      P1.GRUPO_TRABALHO IN (289) 
AND P1.arquivo NOT IN (''M'')" queryout "C:\Startup\Query1.txt" -T -c -t -S SRVBDCPJ'''

Exec(@ExportSQL)





Declare @filenames varchar(max)
Set @filenames = 'C:\Startup\Query1.txt'

EXEC msdb.dbo.sp_send_dbmail
  @profile_name = 'naoresponda',
  @recipients= 'fred.martins@startupnet.com.br',
  @subject= 'Test Email', 
  @body = 'TESTE',
  @file_attachments = @filenames;